spring.application.name=service-payment
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5433/zarcommerce
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

iyzico.api-key=${IYZICO_API_KEY:sandbox-afXhSzHFiClOVTIYmNmzitmOz9GnTKPM}
iyzico.secret-key=${IYZICO_SECRET_KEY:sandbox-KPGX0EC3rNbcBjFomusmA2hxeMrcnuZp}
iyzico.base-url=${IYZICO_BASE_URL:https://sandbox-api.iyzipay.com}
iyzico.callback-url=${IYZICO_CALLBACK_URL:http://localhost:8085/api/v1/payments/callback}
iyzico.frontend-base-url=${IYZICO_FRONTEND_BASE_URL:http://localhost:3000}
