version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: zarcommerce_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zarcommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zarcommerce_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: zarcommerce_rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - zarcommerce_net

volumes:
  postgres_data:

networks:
  zarcommerce_net:
    driver: bridge
